version: '3.1'

services:
  backend:
    build: .
    ports:
      - 80:80
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
